### PR TITLE
fix ch3 overlapped next button bug

### PR DESCRIPTION
**Pull request by Solcany**
please test it on ipad, i made the modals shorter, let's see if it's enough

### CODE REVIEW

**Comment by Solcany** [comment]
please test it on ipad, i made the modals shorter, let's see if it's short enough

**Review by phivk — APPROVED** [review]
fixed!
IMG_0028

**Comment by phivk** [comment]
thanks for fixing the typo!

**Comment by phivk** [comment]
actual this is the fixed view :)
IMG_0029

**Pull request merged**
